package pl.allegro.webapi.service_php;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-05T10:41:34.282+02:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "serviceService",
                  wsdlLocation = "https://webapi.allegro.pl/service.php?wsdl",
                  targetNamespace = "https://webapi.allegro.pl/service.php")
public class ServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://webapi.allegro.pl/service.php", "serviceService");
    public final static QName ServicePort = new QName("https://webapi.allegro.pl/service.php", "servicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://webapi.allegro.pl/service.php?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://webapi.allegro.pl/service.php?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServicePort
     */
    @WebEndpoint(name = "servicePort")
    public ServicePort getServicePort() {
        return super.getPort(ServicePort, ServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePort
     */
    @WebEndpoint(name = "servicePort")
    public ServicePort getServicePort(WebServiceFeature... features) {
        return super.getPort(ServicePort, ServicePort.class, features);
    }

}
