package pl.allegro.webapi.service_php;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-05T10:41:34.189+02:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "https://webapi.allegro.pl/service.php", name = "servicePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicePort {

    @WebMethod(action = "#doGetItemsInfo")
    @WebResult(name = "doGetItemsInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetItemsInfoResponse doGetItemsInfo(
        @WebParam(partName = "parameters", name = "DoGetItemsInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetItemsInfoRequest parameters
    );

    @WebMethod(action = "#doGetMySoldItems")
    @WebResult(name = "doGetMySoldItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMySoldItemsResponse doGetMySoldItems(
        @WebParam(partName = "parameters", name = "DoGetMySoldItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMySoldItemsRequest parameters
    );

    @WebMethod(action = "#doGetSiteJournalDeals")
    @WebResult(name = "doGetSiteJournalDealsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSiteJournalDealsResponse doGetSiteJournalDeals(
        @WebParam(partName = "parameters", name = "DoGetSiteJournalDealsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetSiteJournalDealsRequest parameters
    );

    @WebMethod(action = "#doSellSomeAgain")
    @WebResult(name = "doSellSomeAgainResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSellSomeAgainResponse doSellSomeAgain(
        @WebParam(partName = "parameters", name = "DoSellSomeAgainRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoSellSomeAgainRequest parameters
    );

    @WebMethod(action = "#doAddPackageInfoToPostBuyForm")
    @WebResult(name = "doAddPackageInfoToPostBuyFormResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoAddPackageInfoToPostBuyFormResponse doAddPackageInfoToPostBuyForm(
        @WebParam(partName = "parameters", name = "DoAddPackageInfoToPostBuyFormRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoAddPackageInfoToPostBuyFormRequest parameters
    );

    @WebMethod(action = "#doChangeQuantityItem")
    @WebResult(name = "doChangeQuantityItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoChangeQuantityItemResponse doChangeQuantityItem(
        @WebParam(partName = "parameters", name = "DoChangeQuantityItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoChangeQuantityItemRequest parameters
    );

    @WebMethod(action = "#doGetBidItem2")
    @WebResult(name = "doGetBidItem2Response", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetBidItem2Response doGetBidItem2(
        @WebParam(partName = "parameters", name = "DoGetBidItem2Request", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetBidItem2Request parameters
    );

    @WebMethod(action = "#doShowUser")
    @WebResult(name = "doShowUserResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoShowUserResponse doShowUser(
        @WebParam(partName = "parameters", name = "DoShowUserRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoShowUserRequest parameters
    );

    @WebMethod(action = "#doLoginEnc")
    @WebResult(name = "doLoginEncResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoLoginEncResponse doLoginEnc(
        @WebParam(partName = "parameters", name = "DoLoginEncRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoLoginEncRequest parameters
    );

    @WebMethod(action = "#doGetFilledPostBuyForms")
    @WebResult(name = "doGetFilledPostBuyFormsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetFilledPostBuyFormsResponse doGetFilledPostBuyForms(
        @WebParam(partName = "parameters", name = "DoGetFilledPostBuyFormsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetFilledPostBuyFormsRequest parameters
    );

    @WebMethod(action = "#doGetShipmentData")
    @WebResult(name = "doGetShipmentDataResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetShipmentDataResponse doGetShipmentData(
        @WebParam(partName = "parameters", name = "DoGetShipmentDataRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetShipmentDataRequest parameters
    );

    @WebMethod(action = "#doMyAccountItemsCount")
    @WebResult(name = "doMyAccountItemsCountResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoMyAccountItemsCountResponse doMyAccountItemsCount(
        @WebParam(partName = "parameters", name = "DoMyAccountItemsCountRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoMyAccountItemsCountRequest parameters
    );

    @WebMethod(action = "#doChangeItemFields")
    @WebResult(name = "doChangeItemFieldsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoChangeItemFieldsResponse doChangeItemFields(
        @WebParam(partName = "parameters", name = "DoChangeItemFieldsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoChangeItemFieldsRequest parameters
    );

    @WebMethod(action = "#doGetCatsDataCount")
    @WebResult(name = "doGetCatsDataCountResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetCatsDataCountResponse doGetCatsDataCount(
        @WebParam(partName = "parameters", name = "DoGetCatsDataCountRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetCatsDataCountRequest parameters
    );

    @WebMethod(action = "#doGetMyBidItems")
    @WebResult(name = "doGetMyBidItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyBidItemsResponse doGetMyBidItems(
        @WebParam(partName = "parameters", name = "DoGetMyBidItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyBidItemsRequest parameters
    );

    @WebMethod(action = "#doGetMyPayoutsDetails")
    @WebResult(name = "doGetMyPayoutsDetailsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyPayoutsDetailsResponse doGetMyPayoutsDetails(
        @WebParam(partName = "parameters", name = "DoGetMyPayoutsDetailsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyPayoutsDetailsRequest parameters
    );

    @WebMethod(action = "#doGetShipmentPriceTypes")
    @WebResult(name = "doGetShipmentPriceTypesResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetShipmentPriceTypesResponse doGetShipmentPriceTypes(
        @WebParam(partName = "parameters", name = "DoGetShipmentPriceTypesRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetShipmentPriceTypesRequest parameters
    );

    @WebMethod(action = "#doGetUserLogin")
    @WebResult(name = "doGetUserLoginResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetUserLoginResponse doGetUserLogin(
        @WebParam(partName = "parameters", name = "DoGetUserLoginRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetUserLoginRequest parameters
    );

    @WebMethod(action = "#doGetMySellItems")
    @WebResult(name = "doGetMySellItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMySellItemsResponse doGetMySellItems(
        @WebParam(partName = "parameters", name = "DoGetMySellItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMySellItemsRequest parameters
    );

    @WebMethod(action = "#doLoginWithAccessToken")
    @WebResult(name = "doLoginWithAccessTokenResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoLoginWithAccessTokenResponse doLoginWithAccessToken(
        @WebParam(partName = "parameters", name = "DoLoginWithAccessTokenRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoLoginWithAccessTokenRequest parameters
    );

    @WebMethod(action = "#doCheckItemDescription")
    @WebResult(name = "doCheckItemDescriptionResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoCheckItemDescriptionResponse doCheckItemDescription(
        @WebParam(partName = "parameters", name = "DoCheckItemDescriptionRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoCheckItemDescriptionRequest parameters
    );

    @WebMethod(action = "#doGetPaymentMethods")
    @WebResult(name = "doGetPaymentMethodsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPaymentMethodsResponse doGetPaymentMethods(
        @WebParam(partName = "parameters", name = "DoGetPaymentMethodsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetPaymentMethodsRequest parameters
    );

    @WebMethod(action = "#doSendEmailToUser")
    @WebResult(name = "doSendEmailToUserResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSendEmailToUserResponse doSendEmailToUser(
        @WebParam(partName = "parameters", name = "DoSendEmailToUserRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoSendEmailToUserRequest parameters
    );

    @WebMethod(action = "#doGetPostBuyFormsDataForSellers")
    @WebResult(name = "doGetPostBuyFormsDataForSellersResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPostBuyFormsDataForSellersResponse doGetPostBuyFormsDataForSellers(
        @WebParam(partName = "parameters", name = "DoGetPostBuyFormsDataForSellersRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetPostBuyFormsDataForSellersRequest parameters
    );

    @WebMethod(action = "#doGetUserID")
    @WebResult(name = "doGetUserIDResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetUserIDResponse doGetUserID(
        @WebParam(partName = "parameters", name = "DoGetUserIDRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetUserIDRequest parameters
    );

    @WebMethod(action = "#doMyBillingItem")
    @WebResult(name = "doMyBillingItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoMyBillingItemResponse doMyBillingItem(
        @WebParam(partName = "parameters", name = "DoMyBillingItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoMyBillingItemRequest parameters
    );

    @WebMethod(action = "#doRequestPayout")
    @WebResult(name = "doRequestPayoutResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoRequestPayoutResponse doRequestPayout(
        @WebParam(partName = "parameters", name = "DoRequestPayoutRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoRequestPayoutRequest parameters
    );

    @WebMethod(action = "#doAddToBlackList")
    @WebResult(name = "doAddToBlackListResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoAddToBlackListResponse doAddToBlackList(
        @WebParam(partName = "parameters", name = "DoAddToBlackListRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoAddToBlackListRequest parameters
    );

    @WebMethod(action = "#doGetSiteJournalInfo")
    @WebResult(name = "doGetSiteJournalInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSiteJournalInfoResponse doGetSiteJournalInfo(
        @WebParam(partName = "parameters", name = "DoGetSiteJournalInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetSiteJournalInfoRequest parameters
    );

    @WebMethod(action = "#doMyBilling")
    @WebResult(name = "doMyBillingResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoMyBillingResponse doMyBilling(
        @WebParam(partName = "parameters", name = "DoMyBillingRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoMyBillingRequest parameters
    );

    @WebMethod(action = "#doGetMyNotWonItems")
    @WebResult(name = "doGetMyNotWonItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyNotWonItemsResponse doGetMyNotWonItems(
        @WebParam(partName = "parameters", name = "DoGetMyNotWonItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyNotWonItemsRequest parameters
    );

    @WebMethod(action = "#doSetFreeDeliveryAmount")
    @WebResult(name = "doSetFreeDeliveryAmountResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSetFreeDeliveryAmountResponse doSetFreeDeliveryAmount(
        @WebParam(partName = "parameters", name = "DoSetFreeDeliveryAmountRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoSetFreeDeliveryAmountRequest parameters
    );

    @WebMethod(action = "#doGetMyData")
    @WebResult(name = "doGetMyDataResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyDataResponse doGetMyData(
        @WebParam(partName = "parameters", name = "DoGetMyDataRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyDataRequest parameters
    );

    @WebMethod(action = "#doGetCatsData")
    @WebResult(name = "doGetCatsDataResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetCatsDataResponse doGetCatsData(
        @WebParam(partName = "parameters", name = "DoGetCatsDataRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetCatsDataRequest parameters
    );

    @WebMethod(action = "#doFinishItems")
    @WebResult(name = "doFinishItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoFinishItemsResponse doFinishItems(
        @WebParam(partName = "parameters", name = "DoFinishItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoFinishItemsRequest parameters
    );

    @WebMethod(action = "#doLogin")
    @WebResult(name = "doLoginResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoLoginResponse doLogin(
        @WebParam(partName = "parameters", name = "DoLoginRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoLoginRequest parameters
    );

    @WebMethod(action = "#doGetMyPayouts")
    @WebResult(name = "doGetMyPayoutsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyPayoutsResponse doGetMyPayouts(
        @WebParam(partName = "parameters", name = "DoGetMyPayoutsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyPayoutsRequest parameters
    );

    @WebMethod(action = "#doGetSiteJournal")
    @WebResult(name = "doGetSiteJournalResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSiteJournalResponse doGetSiteJournal(
        @WebParam(partName = "parameters", name = "DoGetSiteJournalRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetSiteJournalRequest parameters
    );

    @WebMethod(action = "#doMyAccount2")
    @WebResult(name = "doMyAccount2Response", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoMyAccount2Response doMyAccount2(
        @WebParam(partName = "parameters", name = "DoMyAccount2Request", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoMyAccount2Request parameters
    );

    @WebMethod(action = "#doGetCategoryPath")
    @WebResult(name = "doGetCategoryPathResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetCategoryPathResponse doGetCategoryPath(
        @WebParam(partName = "parameters", name = "DoGetCategoryPathRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetCategoryPathRequest parameters
    );

    @WebMethod(action = "#doGetMyIncomingPayments")
    @WebResult(name = "doGetMyIncomingPaymentsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyIncomingPaymentsResponse doGetMyIncomingPayments(
        @WebParam(partName = "parameters", name = "DoGetMyIncomingPaymentsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyIncomingPaymentsRequest parameters
    );

    @WebMethod(action = "#doGetRefundsList")
    @WebResult(name = "doGetRefundsListResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetRefundsListResponse doGetRefundsList(
        @WebParam(partName = "parameters", name = "DoGetRefundsListRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetRefundsListRequest parameters
    );

    @WebMethod(action = "#doQuerySysStatus")
    @WebResult(name = "doQuerySysStatusResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoQuerySysStatusResponse doQuerySysStatus(
        @WebParam(partName = "parameters", name = "DoQuerySysStatusRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoQuerySysStatusRequest parameters
    );

    @WebMethod(action = "#doBidItem")
    @WebResult(name = "doBidItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoBidItemResponse doBidItem(
        @WebParam(partName = "parameters", name = "DoBidItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoBidItemRequest parameters
    );

    @WebMethod(action = "#doQueryAllSysStatus")
    @WebResult(name = "doQueryAllSysStatusResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoQueryAllSysStatusResponse doQueryAllSysStatus(
        @WebParam(partName = "parameters", name = "DoQueryAllSysStatusRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoQueryAllSysStatusRequest parameters
    );

    @WebMethod(action = "#doGetCatsDataLimit")
    @WebResult(name = "doGetCatsDataLimitResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetCatsDataLimitResponse doGetCatsDataLimit(
        @WebParam(partName = "parameters", name = "DoGetCatsDataLimitRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetCatsDataLimitRequest parameters
    );

    @WebMethod(action = "#doNewAuctionExt")
    @WebResult(name = "doNewAuctionExtResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoNewAuctionExtResponse doNewAuctionExt(
        @WebParam(partName = "parameters", name = "DoNewAuctionExtRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoNewAuctionExtRequest parameters
    );

    @WebMethod(action = "#doGetSystemTime")
    @WebResult(name = "doGetSystemTimeResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSystemTimeResponse doGetSystemTime(
        @WebParam(partName = "parameters", name = "DoGetSystemTimeRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetSystemTimeRequest parameters
    );

    @WebMethod(action = "#doGetRefundsReasons")
    @WebResult(name = "doGetRefundsReasonsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetRefundsReasonsResponse doGetRefundsReasons(
        @WebParam(partName = "parameters", name = "DoGetRefundsReasonsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetRefundsReasonsRequest parameters
    );

    @WebMethod(action = "#doGetMyNotSoldItems")
    @WebResult(name = "doGetMyNotSoldItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyNotSoldItemsResponse doGetMyNotSoldItems(
        @WebParam(partName = "parameters", name = "DoGetMyNotSoldItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyNotSoldItemsRequest parameters
    );

    @WebMethod(action = "#doVerifyItem")
    @WebResult(name = "doVerifyItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoVerifyItemResponse doVerifyItem(
        @WebParam(partName = "parameters", name = "DoVerifyItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoVerifyItemRequest parameters
    );

    @WebMethod(action = "#doSellSomeAgainInShop")
    @WebResult(name = "doSellSomeAgainInShopResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSellSomeAgainInShopResponse doSellSomeAgainInShop(
        @WebParam(partName = "parameters", name = "DoSellSomeAgainInShopRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoSellSomeAgainInShopRequest parameters
    );

    @WebMethod(action = "#doSendRefundForm")
    @WebResult(name = "doSendRefundFormResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSendRefundFormResponse doSendRefundForm(
        @WebParam(partName = "parameters", name = "DoSendRefundFormRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoSendRefundFormRequest parameters
    );

    @WebMethod(action = "#doGetFreeDeliveryAmount")
    @WebResult(name = "doGetFreeDeliveryAmountResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetFreeDeliveryAmountResponse doGetFreeDeliveryAmount(
        @WebParam(partName = "parameters", name = "DoGetFreeDeliveryAmountRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetFreeDeliveryAmountRequest parameters
    );

    @WebMethod(action = "#doGetMyPaymentsInfo")
    @WebResult(name = "doGetMyPaymentsInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyPaymentsInfoResponse doGetMyPaymentsInfo(
        @WebParam(partName = "parameters", name = "DoGetMyPaymentsInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyPaymentsInfoRequest parameters
    );

    @WebMethod(action = "#doGetBlackListUsers")
    @WebResult(name = "doGetBlackListUsersResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetBlackListUsersResponse doGetBlackListUsers(
        @WebParam(partName = "parameters", name = "DoGetBlackListUsersRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetBlackListUsersRequest parameters
    );

    @WebMethod(action = "#doFinishItem")
    @WebResult(name = "doFinishItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoFinishItemResponse doFinishItem(
        @WebParam(partName = "parameters", name = "DoFinishItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoFinishItemRequest parameters
    );

    @WebMethod(action = "#doGetMyFutureItems")
    @WebResult(name = "doGetMyFutureItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyFutureItemsResponse doGetMyFutureItems(
        @WebParam(partName = "parameters", name = "DoGetMyFutureItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyFutureItemsRequest parameters
    );

    @WebMethod(action = "#doGetStatesInfo")
    @WebResult(name = "doGetStatesInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetStatesInfoResponse doGetStatesInfo(
        @WebParam(partName = "parameters", name = "DoGetStatesInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetStatesInfoRequest parameters
    );

    @WebMethod(action = "#doChangePriceItem")
    @WebResult(name = "doChangePriceItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoChangePriceItemResponse doChangePriceItem(
        @WebParam(partName = "parameters", name = "DoChangePriceItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoChangePriceItemRequest parameters
    );

    @WebMethod(action = "#doSetShipmentPriceType")
    @WebResult(name = "doSetShipmentPriceTypeResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSetShipmentPriceTypeResponse doSetShipmentPriceType(
        @WebParam(partName = "parameters", name = "DoSetShipmentPriceTypeRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoSetShipmentPriceTypeRequest parameters
    );

    @WebMethod(action = "#doGetPostBuyData")
    @WebResult(name = "doGetPostBuyDataResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPostBuyDataResponse doGetPostBuyData(
        @WebParam(partName = "parameters", name = "DoGetPostBuyDataRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetPostBuyDataRequest parameters
    );

    @WebMethod(action = "#doGetSellFormFieldsForCategory")
    @WebResult(name = "doGetSellFormFieldsForCategoryResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSellFormFieldsForCategoryResponse doGetSellFormFieldsForCategory(
        @WebParam(partName = "parameters", name = "DoGetSellFormFieldsForCategoryRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetSellFormFieldsForCategoryRequest parameters
    );

    @WebMethod(action = "#doGetDeals")
    @WebResult(name = "doGetDealsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetDealsResponse doGetDeals(
        @WebParam(partName = "parameters", name = "DoGetDealsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetDealsRequest parameters
    );

    @WebMethod(action = "#doRemoveFromBlackList")
    @WebResult(name = "doRemoveFromBlackListResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoRemoveFromBlackListResponse doRemoveFromBlackList(
        @WebParam(partName = "parameters", name = "DoRemoveFromBlackListRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoRemoveFromBlackListRequest parameters
    );

    @WebMethod(action = "#doShowItemInfoExt")
    @WebResult(name = "doShowItemInfoExtResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoShowItemInfoExtResponse doShowItemInfoExt(
        @WebParam(partName = "parameters", name = "DoShowItemInfoExtRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoShowItemInfoExtRequest parameters
    );

    @WebMethod(action = "#doGetItemFields")
    @WebResult(name = "doGetItemFieldsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetItemFieldsResponse doGetItemFields(
        @WebParam(partName = "parameters", name = "DoGetItemFieldsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetItemFieldsRequest parameters
    );

    @WebMethod(action = "#doGetMyIncomingPaymentsRefunds")
    @WebResult(name = "doGetMyIncomingPaymentsRefundsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyIncomingPaymentsRefundsResponse doGetMyIncomingPaymentsRefunds(
        @WebParam(partName = "parameters", name = "DoGetMyIncomingPaymentsRefundsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyIncomingPaymentsRefundsRequest parameters
    );

    @WebMethod(action = "#doGetPostBuyFormsIds")
    @WebResult(name = "doGetPostBuyFormsIdsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPostBuyFormsIdsResponse doGetPostBuyFormsIds(
        @WebParam(partName = "parameters", name = "DoGetPostBuyFormsIdsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetPostBuyFormsIdsRequest parameters
    );

    @WebMethod(action = "#doGetCountries")
    @WebResult(name = "doGetCountriesResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetCountriesResponse doGetCountries(
        @WebParam(partName = "parameters", name = "DoGetCountriesRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetCountriesRequest parameters
    );

    @WebMethod(action = "#doCheckNewAuctionExt")
    @WebResult(name = "doCheckNewAuctionExtResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoCheckNewAuctionExtResponse doCheckNewAuctionExt(
        @WebParam(partName = "parameters", name = "DoCheckNewAuctionExtRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoCheckNewAuctionExtRequest parameters
    );

    @WebMethod(action = "#doGetSiteJournalDealsInfo")
    @WebResult(name = "doGetSiteJournalDealsInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSiteJournalDealsInfoResponse doGetSiteJournalDealsInfo(
        @WebParam(partName = "parameters", name = "DoGetSiteJournalDealsInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetSiteJournalDealsInfoRequest parameters
    );

    @WebMethod(action = "#doGetMyWonItems")
    @WebResult(name = "doGetMyWonItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyWonItemsResponse doGetMyWonItems(
        @WebParam(partName = "parameters", name = "DoGetMyWonItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyWonItemsRequest parameters
    );

    @WebMethod(action = "#doGetTransactionsIDs")
    @WebResult(name = "doGetTransactionsIDsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetTransactionsIDsResponse doGetTransactionsIDs(
        @WebParam(partName = "parameters", name = "DoGetTransactionsIDsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetTransactionsIDsRequest parameters
    );

    @WebMethod(action = "#doGetRefundsDeals")
    @WebResult(name = "doGetRefundsDealsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetRefundsDealsResponse doGetRefundsDeals(
        @WebParam(partName = "parameters", name = "DoGetRefundsDealsRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetRefundsDealsRequest parameters
    );

    @WebMethod(action = "#doGetMyCurrentShipmentPriceType")
    @WebResult(name = "doGetMyCurrentShipmentPriceTypeResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyCurrentShipmentPriceTypeResponse doGetMyCurrentShipmentPriceType(
        @WebParam(partName = "parameters", name = "DoGetMyCurrentShipmentPriceTypeRequest", targetNamespace = "https://webapi.allegro.pl/service.php")
        DoGetMyCurrentShipmentPriceTypeRequest parameters
    );
}
